version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: resume
      POSTGRES_PASSWORD: resume
      POSTGRES_DB: resumelab
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - latexbuild:/app/build   # PDFs stored here
    ports: ["8000:8000"]
    depends_on: [db]

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports: ["3000:3000"]
    environment:
      - REACT_APP_API_BASE=http://localhost:8000

volumes:
  dbdata:
  latexbuild:
